# fastagent.secrets.yaml - API key configuration for fast-agent
# This file stores API keys for various LLM providers

# OpenAI API configuration for GPT models
openai:
  api_key: "${OPENAI_API_KEY}"

# Anthropic API configuration for Claude models (Haiku, Sonnet, Opus)
anthropic:
  api_key: "${ANTHROPIC_API_KEY}"